;;;; Emacs Bookmark Format Version 1;;;; -*- coding: utf-8-emacs; mode: lisp-data -*-
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(("dpxlab: dpxlab"
  (filename . "/ssh:kirby@dpxlab:/home/kirby")
  (front-context-string)
  (rear-context-string . "  7 01:51 vendor")
  (position . 817)
  (last-modified 27293 65162 613823 493000))
)
